### ISSUE TITLE
Check version of targeted organization to ensure it is v9

### ISSUE THREAD

**Issue by MscrmTools** [DynamicsNinja/FastRecordCounter#2]
I guess the message RetrieveTotalRecordCountRequest is only available on v9. 

You should maybe check the version of the connected organization to warn user this tool can be used only with v9

**Comment by imranakram** [comment]
Reference to your own commit @DynamicsNinja [fc3556] :)(https://github.com/Innofactor/PluginRegistration/commit/fbecb487eb07e896351951faa15a7c1631fc3556)
