### ISSUE TITLE
Counter for D365 online

### ISSUE THREAD

**Issue by thomassandsor** [DynamicsNinja/FastRecordCounter#3]
When counting accounts in my online environment I get a "wrong" number. Not sure if it only counts the active accounts? I have an environment that has 30000 ish active and 10000 inactive. The counter only returns approximately 30000

I did an export of all accounts via advanced find and get a total of 40000 ish.

**Comment by DynamicsNinja** [comment]
The issue here is that I'm using RetrieveTotalRecordCountRequest which has opened bug on MS that sometimes it returns cached result instead of the real one. Let's hope that it will be fixed soon.
