### ISSUE TITLE
Record count stuck after first run

### ISSUE THREAD

**Issue by PaulFSSE** [DynamicsNinja/FastRecordCounter#4]
Running the Fast Record Counter on a Power Platform dataverse environment while there is a long running import / delete or similar process running returns a count of the records in the selected tables, but if you run it a second (or subsequent) times it always returns the same record count even if the table row count has actually changed.

This persists even if you close and reopen the tool / XrmToolbox.

---
- Deployment: Online
- DB Version: 9.2.22074.156
- Connection Controls Version: 1.2022.7.53
- XrmToolBox Version: 1.2022.2.54
- Tool Version: 1.2020.12.7

**Comment by DynamicsNinja** [comment]
That is because the count is cached and it's refreshed once a day.

**Comment by PaulFSSE** [comment]
> That is because the count is cached and it's refreshed once a day.

Is there a way around that to get a real-time count?

**Comment by DynamicsNinja** [comment]
There is a tool called **Record Counter** that counts records 5k by 5k and it will return the exact number, but it can take a while if you have large dataset.
