### ISSUE TITLE
Int32 error

### ISSUE THREAD

**Issue by rappen** [DynamicsNinja/FastRecordCounter#5]
I feel a bit stupid, but why do I get this error when I try to count?
For all entities, I have tried so far...

![image](https://github.com/DynamicsNinja/FastRecordCounter/assets/2572253/66172c30-6317-44e8-9f3d-78aef453f031)

---
- Deployment: Online
- DB Version: 9.2.24043.228
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.12.68
- Tool Version: 1.2024.5.9

**Comment by DynamicsNinja** [comment]
Interesting, it pops out when selecting rows one by one, but when you do a select all and count it works like a charm. Need to check what's happening there in the background.

**Comment by DynamicsNinja** [comment]
Dumb error when implementing the last updated counter information

**Comment by rappen** [comment]
Oops, but thanks! 😊
