### ISSUE TITLE
It just won't count records

### ISSUE THREAD

**Issue by rappen** [DynamicsNinja/FastRecordCounter#6]
Sorry, I have no idea why it doesn't work.
https://app.screencast.com/qYXhHt6eezoDF

The log file only says:
```
2024-11-19 08:50:38.456 am	S CRM Prod	Warning	Settings not found => a new settings file has been created!
```
...but that was probably written before I tried to count.

Help?

---
- Deployment: Online
- DB Version: 9.2.24103.216
- Connection Controls Version: 1.2024.9.59
- XrmToolBox Version: 1.2024.9.69
- Tool Version: 1.2024.5.11

**Comment by DynamicsNinja** [comment]
Tried on several environments and it's working as expected. Which connection are you using?

**Comment by DynamicsNinja** [comment]
Not sure what is too much data 😜 I have a few environments with around 20M records per table and it's working just fine. Do you have more than that?

**Comment by rappen** [comment]
Nope, not any more info...
Do you have better logs somewhere? ;)
How do you handle errors?
I might get a fork and see if I can improve it... 😏

**Comment by DynamicsNinja** [comment]
My error handling is popping the error message 🤣

**Comment by rappen** [comment]
I'm improving your code a bit right now....

**Comment by rappen** [comment]
> My error handling is popping the error message 🤣

That's better than nothing! 😘
